---
ID: "f2d6b2d6-db6c-4587-8d71-b7783180b6c5"
Parent: "46c47add-a296-416c-a569-5b5cd17f0a41"
Template: "1d840426-5def-4a76-811c-e73da21f64ac"
Path: /sitecore/content/Sitecore/Styleguide/Settings/Twitter Apps/Default
SharedFields:
- ID: "39ac23af-05d1-4cf6-af8d-0a5433bd86ce"
  Hint: ConsumerSecret
  Value: r4gHB2AagiXMbLmr0aTtPttsvLhrfUTLLTMgoFufAkIrtTnsjF
- ID: "b63dfc4a-758d-4990-83cd-c0f82c9f1364"
  Hint: ConsumerKey
  Value: 4QilkFDUAYGOjTd4hUsSO5MY2
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200203T103126Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8a9791db-d063-439d-94be-7c8a0ded715d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200710T194545Z
